# Sets if the block breaking progress bar should be shown
show-progress-bar: true

# Sets the color of the mining progress bar
# Possible colors: blue, red, pink, green, yellow, purple, white
progress-bar-color: blue

# Sets if normal vanilla blocks can be broken with default vanilla mechanics
break-vanilla-blocks: true

# Sets the range at which the block cracking animation will be shown to other players
cracking-animation-range: 50

# Sets if the player can stop mining the current block and start mining other blocks without loosing progress on previously mined blocks
allow-breaking-multiple-blocks: true

# Sets how many blocks players can be mining simultaneously
# Set to 1 if you just want the player to be able to stop mining a block and start again without loosing progress
simultaneous-broken-blocks-limit: 1

# Sets the amount of ticks after which progress on a previously mined block is reset
mining-progress-reset-timer: 1200