name: AdvancedMining
version: '1.0'
main: win.codingboulder.advancedmining.AdvancedMining
api-version: '1.21'
authors: [ CodingBoulder ]
description: A plugin that adds a custom mining system
website: https://hangar.papermc.io/CodingBoulder/AdvancedMining
